In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
os.getcwd()

'C:\\Users\\91909\\DS_Real_time\\01. Associate_rule_mining_purchase_requisition'

In [3]:
data = pd.read_excel(r"MBA_Dataset.xlsx")
data.head()

                  ID Project_Name                    Item_Name  month
0  MAT-MR-2024-03954     Ambition                 PC1 V3 Mount     12
1  MAT-MR-2024-03954     Ambition  Silicon wires 24 AWG Orange     12
2  MAT-MR-2024-03954     Ambition            GPS Mount (Right)     12
3  MAT-MR-2024-03954     Ambition                     ESC Cowl     12
4  MAT-MR-2024-03954     Ambition  Silicon wires 28 AWG Orange     12

In [4]:
basket = data.groupby(['Project_Name','month'])['Item_Name'].apply(list).reset_index()
basket

       Project_Name  month                                          Item_Name
0          Ambition      2  [PAINTING WORK, Master cost, MJF Plastic; 3D03...
1          Ambition      3  [SS Plain Round Spacer M3x6, SS Plain Washer M...
2          Ambition      4  [GPS Mount (Left), GPS Mount (Right), GPS Casi...
3          Ambition      5  [N3T-400-4012-00_SLA-Clear, N3T-400-4012-00_SL...
4          Ambition      7  [Velcro-Aircraft ARM, Propeller Tray, Velcro -...
..              ...    ...                                                ...
60  USGB - NewSpace      8  [LH Centre Fuselage_V7.1, RH Centre Fuselage_V...
61  USGB - NewSpace      9  [Spring holder mount V1.0, WDM_Crank_V7.1, SS ...
62  USGB - NewSpace     10  [\tEmery Paper 80 grit, Strake Fin Insert, RH ...
63  USGB - NewSpace     11                    [O0002010-4 Metal horn package]
64  USGB - NewSpace     12  [7601 (AlSi10Mg), M3x8 Button head/Phillip hea...

[65 rows x 3 columns]

In [5]:
from mlxtend.frequent_patterns import association_rules,apriori
from mlxtend.preprocessing import TransactionEncoder

In [6]:
te = TransactionEncoder()
te_ary = te.fit(basket['Item_Name']).transform(basket['Item_Name'])
encoded_basket = pd.DataFrame(te_ary,columns = te.columns_)
encoded_basket

,\tEmery Paper 80 grit,\tSurgical face mask,\tWax polish(White),5 m measuring tape,9mm Knife ABS Body(SX-63),ADSB_BRACKET,COWL_MOUNTING_FRONT,FLYTRON_STROBE_LIGHT_MOUNT,HIT0-PT3-AJ-103,Item ID: Model: SWM-S3-2.2,...,amazon basics Rubber Mallet,components ( LC-Parts),connector,fixed_aft_lg_fork_2.25in,hinges 30 Alloy,metlok 743,optical wired mouse -MS116,silver maker,tail_lg_top_tube_CUTDR AFT,wing coupler Al 7075-T9
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
61,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
62,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
63,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
freq_items = apriori(encoded_basket,min_support = 0.1,use_colnames = True)

In [8]:
freq_items

      support                                           itemsets
0    0.153846                           ( Pixhawk orange cube +)
1    0.153846                          (1000 series solvent IPA)
2    0.138462                     (2 Face L-Clamp - LRU011NMB3P)
3    0.153846                                   (25mm MDF Sheet)
4    0.184615                                 (AL Profile 20x20)
..        ...                                                ...
97   0.107692  (Lacing thread, Permabond 910 50 ml, Nylon Was...
98   0.107692  (Lacing thread, Nylon Washer M3, SS Hex Nut M2.5)
99   0.107692  (Lacing thread, Nylon Washer M3, SS Square Nut...
100  0.107692  (Nylon washer M2.5, Nylon Washer M3, SS Hex Nu...
101  0.107692  (Nylon Washer M3, SS Square Nut M4, XT-60H Mal...

[102 rows x 2 columns]

In [10]:
rules = association_rules(freq_items,metric = 'lift',min_threshold = 2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Lacing thread),(1000 series solvent IPA),0.153846,0.153846,0.107692,0.700000,4.550000,1.0,0.084024,2.820513,0.922078,0.538462,0.645455,0.700000
1,(1000 series solvent IPA),(Lacing thread),0.153846,0.153846,0.107692,0.700000,4.550000,1.0,0.084024,2.820513,0.922078,0.538462,0.645455,0.700000
2,(Nylon Washer M3),(1000 series solvent IPA),0.184615,0.153846,0.107692,0.583333,3.791667,1.0,0.079290,2.030769,0.902965,0.466667,0.507576,0.641667
3,(1000 series solvent IPA),(Nylon Washer M3),0.153846,0.184615,0.107692,0.700000,3.791667,1.0,0.079290,2.717949,0.870130,0.466667,0.632075,0.641667
4,(Permabond 910 50 ml),(1000 series solvent IPA),0.230769,0.153846,0.107692,0.466667,3.033333,1.0,0.072189,1.586538,0.871429,0.388889,0.369697,0.583333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,"(Nylon Washer M3, XT-60H Male Connectors)",(SS Square Nut M4),0.107692,0.153846,0.107692,1.000000,6.500000,1.0,0.091124,inf,0.948276,0.700000,1.000000,0.850000
114,"(SS Square Nut M4, XT-60H Male Connectors)",(Nylon Washer M3),0.123077,0.184615,0.107692,0.875000,4.739583,1.0,0.084970,6.523077,0.899749,0.538462,0.846698,0.729167
115,(Nylon Washer M3),"(SS Square Nut M4, XT-60H Male Connectors)",0.184615,0.123077,0.107692,0.583333,4.739583,1.0,0.084970,2.104615,0.967655,0.538462,0.524854,0.729167
116,(SS Square Nut M4),"(Nylon Washer M3, XT-60H Male Connectors)",0.153846,0.107692,0.107692,0.700000,6.500000,1.0,0.091124,2.974359,1.000000,0.700000,0.663793,0.850000
117,(XT-60H Male Connectors),"(Nylon Washer M3, SS Square Nut M4)",0.138462,0.123077,0.107692,0.777778,6.319444,1.0,0.090651,3.946154,0.977041,0.700000,0.746589,0.826389

In [14]:
rules.sort_values(by = 'lift',ascending = False,inplace = True)

In [15]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
100,"(Lacing thread, Nylon Washer M3)",(SS Square Nut; M3),0.138462,0.107692,0.107692,0.777778,7.222222,1.0,0.092781,4.015385,1.000000,0.777778,0.750958,0.888889
105,(SS Square Nut; M3),"(Lacing thread, Nylon Washer M3)",0.107692,0.138462,0.107692,1.000000,7.222222,1.0,0.092781,inf,0.965517,0.777778,1.000000,0.888889
78,"(Nylon Washer M3, Masking tape 1 inch)",(Lacing thread),0.107692,0.153846,0.107692,1.000000,6.500000,1.0,0.091124,inf,0.948276,0.700000,1.000000,0.850000
113,"(Nylon Washer M3, XT-60H Male Connectors)",(SS Square Nut M4),0.107692,0.153846,0.107692,1.000000,6.500000,1.0,0.091124,inf,0.948276,0.700000,1.000000,0.850000
31,(SS Square Nut; M3),(Lacing thread),0.107692,0.153846,0.107692,1.000000,6.500000,1.0,0.091124,inf,0.948276,0.700000,1.000000,0.850000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,(SS Plain Washer M3),(Banian Cloth; White),0.184615,0.261538,0.107692,0.583333,2.230392,1.0,0.059408,1.772308,0.676550,0.318182,0.435764,0.497549
10,(AL Profile 20x20),(Banian Cloth; White),0.184615,0.261538,0.107692,0.583333,2.230392,1.0,0.059408,1.772308,0.676550,0.318182,0.435764,0.497549
11,(Banian Cloth; White),(AL Profile 20x20),0.261538,0.184615,0.107692,0.411765,2.230392,1.0,0.059408,1.386154,0.747024,0.318182,0.278579,0.497549
17,(Banian Cloth; White),(SS Hex Nut M2.5),0.261538,0.184615,0.107692,0.411765,2.230392,1.0,0.059408,1.386154,0.747024,0.318182,0.278579,0.497549
19,(Banian Cloth; White),(SS Plain Washer M3),0.261538,0.184615,0.107692,0.411765,2.230392,1.0,0.059408,1.386154,0.747024,0.318182,0.278579,0.497549